import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import Script from "next/script";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KBCOM - Agence Web basée à tours",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  axios.defaults = {
    withCredentials: false,
    headers: {
      options: {
        Authorization:
          "bearer 6d1ccd7acd4df67e24e66b38d7f82362490c2ecc7d5ad9eb4da94601db023d0eb47e4254355eff3d48749e1e77f5a03fa9b9838442640aca4e9585f14742607193d7c5cf2e4bdf22a1096fe1023150a90c22e4427cbf44d8578f86ee919d59514f67ce89139fea1b0f479bda4a1ccbb5eaf1a7b6e09a03a06d2a22401c2f900d",
      },
    },
  };
  return (
    <html lang="fr" dir="ltr" className="dark">
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body
        className={
          inter.className +
          " overflow-x-hidden font-body text-jacarta-500 dark:bg-jacarta-900"
        }
        itemScope
        itemType="http://schema.org/WebPage"
      >
        <Header />
        <Toaster position="top-center" reverseOrder={false} />
        {children}
        <Footer />
        <Script src="js/app.bundle.js"></Script>
        <Script src="js/charts.bundle.js"></Script>
        <Script src="js/countdown.bundle.js"></Script>
      </body>
    </html>
  );
}
